let obj = {
  avatar_url: "https://avatars.githubusercontent.com/u/6364656?v=4",
  bio: "Fullstack Software Engineer",
  blog: "",
  company: null,
  created_at: "2014-01-10T00:43:48Z",
  email: null,
  events_url: "https://api.github.com/users/Jgoodall13/events{/privacy}",
  followers: 4,
  followers_url: "https://api.github.com/users/Jgoodall13/followers",
  following: 3,
  following_url:
    "https://api.github.com/users/Jgoodall13/following{/other_user}",
  gists_url: "https://api.github.com/users/Jgoodall13/gists{/gist_id}",
  gravatar_id: "",
  hireable: null,
  html_url: "https://github.com/Jgoodall13",
  id: 6364656,
  location: "Chicago",
  login: "Jgoodall13",
  name: "Jacob Goodall",
  node_id: "MDQ6VXNlcjYzNjQ2NTY=",
  organizations_url: "https://api.github.com/users/Jgoodall13/orgs",
  public_gists: 0,
  public_repos: 72,
  received_events_url:
    "https://api.github.com/users/Jgoodall13/received_events",
  repos_url: "https://api.github.com/users/Jgoodall13/repos",
  site_admin: false,
  starred_url: "https://api.github.com/users/Jgoodall13/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Jgoodall13/subscriptions",
  twitter_username: null,
  type: "User",
  updated_at: "2025-06-02T18:18:39Z",
  url: "https://api.github.com/users/Jgoodall13",
  user_view_type: "public",
};
